name: Q Code Transformation

on:
  push:
    branches:
      - 'q/transform-**'  # Matches branches starting with q/transform-

jobs:
  q-code-transformation:
    runs-on: ubuntu-latest
    
    container:
      image: maven:3.8-openjdk-8  # Same image as GitLab CI
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Maven CLI options
        run: |
          echo "MAVEN_CLI_OPTS=--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true" >> $GITHUB_ENV
      
      - name: Run Maven verify
        run: mvn $MAVEN_CLI_OPTS verify
      
      - name: Copy dependencies
        run: |
          mvn $MAVEN_CLI_OPTS dependency:copy-dependencies \
            -DoutputDirectory=dependencies \
            -Dmdep.useRepositoryLayout=true \
            -Dmdep.copyPom=true \
            -Dmdep.addParentPoms=true
      
      - name: Upload dependencies artifact
        uses: actions/upload-artifact@v4
        with:
          name: q-code-transformation-dependencies
          path: dependencies/
          retention-days: 30  # Optional: set retention period
