name: Q Code Transformation

on:
  push:
    branches:
      - 'Q-TRANSFORM-issue-*'

jobs:
  q-code-transformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Debug - List available files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in root:"
          ls -la
          echo "Files in movie-service-utils:"
          ls -la movie-service-utils/
          echo "Files in movie-service-utils/built-library:"
          ls -la movie-service-utils/built-library/
          echo "Files in movie-service-utils/built-library/0_1_0:"
          ls -la movie-service-utils/built-library/0_1_0/

      - name: Install pre-compiled utils dependency
        run: |
          # Try to install the pre-compiled movie-service-utils JAR to local Maven repository
          if [ -f "movie-service-utils/built-library/0_1_0/movie-service-utils-0.1.0.jar" ]; then
            echo "Using pre-compiled JAR..."
            # Install with both possible group IDs to cover all cases
            echo "Installing with com.amazonaws.samples group ID..."
            mvn install:install-file \
              -Dfile=movie-service-utils/built-library/0_1_0/movie-service-utils-0.1.0.jar \
              -DgroupId=com.amazonaws.samples \
              -DartifactId=movie-service-utils \
              -Dversion=0.1.0 \
              -Dpackaging=jar
            echo "Installing with org.amazonaws.samples group ID..."
            mvn install:install-file \
              -Dfile=movie-service-utils/built-library/0_1_0/movie-service-utils-0.1.0.jar \
              -DgroupId=org.amazonaws.samples \
              -DartifactId=movie-service-utils \
              -Dversion=0.1.0 \
              -Dpackaging=jar
          else
            echo "Pre-compiled JAR not found, trying to build from source with Java 8..."
            cd movie-service-utils
            # Temporarily modify the pom.xml to use Java 8 and correct group ID
            sed -i 's/<java.version>17<\/java.version>/<java.version>8<\/java.version>/g' pom.xml
            sed -i 's/<maven.compiler.source>17<\/maven.compiler.source>/<maven.compiler.source>8<\/maven.compiler.source>/g' pom.xml
            sed -i 's/<maven.compiler.target>17<\/maven.compiler.target>/<maven.compiler.target>8<\/maven.compiler.target>/g' pom.xml
            sed -i 's/<maven.compiler.release>17<\/maven.compiler.release>/<maven.compiler.release>8<\/maven.compiler.release>/g' pom.xml
            sed -i 's/<groupId>org.amazonaws.samples<\/groupId>/<groupId>com.amazonaws.samples<\/groupId>/g' pom.xml
            sed -i 's/<version>0.2.0<\/version>/<version>0.1.0<\/version>/g' pom.xml
            mvn clean install -DskipTests
            cd ..
          fi

      - name: Build and copy dependencies
        run: |
          # Build the main project (utils dependency is now available in local repo)
          mvn clean verify -DskipTests
          mvn dependency:copy-dependencies -DoutputDirectory=dependencies -Dmdep.useRepositoryLayout=true -Dmdep.copyPom=true -Dmdep.addParentPoms=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: q-code-transformation-dependencies
          path: dependencies